### ISSUE TITLE
Check for deprecated APIs

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa-auth-server#2343]
I updated the .eslintrc file to the following and also extended **plugin:node/recommended** and got a few deprecation notices:

```sh
➜  fxa-auth-server git:(master) ✗ grunt eslint
Running "eslint:app" (eslint) task

/Users/pdehaan/dev/github/mozilla/fxa-auth-server_moz/fxa-auth-server/lib/crypto/butil.js
   7:23  error  'Buffer()' was deprecated since v6. Use 'Buffer.alloc()' or 'Buffer.from()' (use 'https://www.npmjs.com/package/safe-buffer' for '<4.5.0') instead  node/no-deprecated-api
  32:16  error  'Buffer()' was deprecated since v6. Use 'Buffer.alloc()' or 'Buffer.from()' (use 'https://www.npmjs.com/package/safe-buffer' for '<4.5.0') instead  node/no-deprecated-api

/Users/pdehaan/dev/github/mozilla/fxa-auth-server_moz/fxa-auth-server/lib/routes/validators.js
  8:16  error  'punycode' module was deprecated since v7. Use 'https://www.npmjs.com/package/punycode' instead  node/no-deprecated-api

/Users/pdehaan/dev/github/mozilla/fxa-auth-server_moz/fxa-auth-server/test/local/crypto/butil.js
  24:20  error  'Buffer()' was deprecated since v6. Use 'Buffer.alloc()' or 'Buffer.from()' (use 'https://www.npmjs.com/package/safe-buffer' for '<4.5.0') instead  node/no-deprecated-api
  25:20  error  'Buffer()' was deprecated since v6. Use 'Buffer.alloc()' or 'Buffer.from()' (use 'https://www.npmjs.com/package/safe-buffer' for '<4.5.0') instead  node/no-deprecated-api

/Users/pdehaan/dev/github/mozilla/fxa-auth-server_moz/fxa-auth-server/test/local/senders/email.js
  10:16  error  'util._extend' was deprecated since v6. Use 'Object.assign()' instead  node/no-deprecated-api

/Users/pdehaan/dev/github/mozilla/fxa-auth-server_moz/fxa-auth-server/test/mocks.js
  13:16  error  'util._extend' was deprecated since v6. Use 'Object.assign()' instead  node/no-deprecated-api

✖ 7 problems (7 errors, 0 warnings)

Warning: Task "eslint:app" failed. Use --force to continue.

Aborted due to warnings.
```

```yml
extends:
  - plugin:fxa/server
  - plugin:node/recommended

plugins:
  - fxa
  - node

root: true

rules:
  node/no-missing-require: off
  node/no-unpublished-require: off
  node/shebang: off

  handle-callback-err: off
  no-process-exit: off
  strict: error
```
